/**
 * Canonical Permissions & Role Capabilities Matrix
 * Varanasi Yatra Platform
 */

const { ROLES } = require('./roles');

const PERMISSIONS = Object.freeze({
    // Leads
    LEADS_VIEW: 'LEADS_VIEW',
    LEADS_CREATE: 'LEADS_CREATE',
    LEADS_ASSIGN: 'LEADS_ASSIGN',
    LEADS_EDIT: 'LEADS_EDIT',

    // Customers
    CUSTOMERS_VIEW: 'CUSTOMERS_VIEW',
    CUSTOMERS_CREATE: 'CUSTOMERS_CREATE',
    CUSTOMERS_EDIT: 'CUSTOMERS_EDIT',

    // Quotes
    QUOTES_VIEW: 'QUOTES_VIEW',
    QUOTES_CREATE: 'QUOTES_CREATE',
    QUOTES_EDIT: 'QUOTES_EDIT',
    QUOTES_SEND: 'QUOTES_SEND',

    // Bookings
    BOOKINGS_VIEW: 'BOOKINGS_VIEW',
    BOOKINGS_CREATE: 'BOOKINGS_CREATE',
    BOOKINGS_EDIT: 'BOOKINGS_EDIT',

    // Payments
    PAYMENTS_VIEW: 'PAYMENTS_VIEW',
    PAYMENTS_CREATE: 'PAYMENTS_CREATE',
    PAYMENTS_EDIT: 'PAYMENTS_EDIT',

    // Trips
    TRIPS_VIEW: 'TRIPS_VIEW',
    TRIPS_EDIT: 'TRIPS_EDIT',

    // Communications
    COMMUNICATION_VIEW: 'COMMUNICATION_VIEW',
    COMMUNICATION_CREATE: 'COMMUNICATION_CREATE',

    // Resources & Master Rates
    RESOURCES_VIEW: 'RESOURCES_VIEW',
    RESOURCES_MANAGE: 'RESOURCES_MANAGE',

    // Hotel Partners
    PARTNERS_VIEW: 'PARTNERS_VIEW',
    PARTNERS_MANAGE: 'PARTNERS_MANAGE',

    // Team Hierarchy & User Lifecycle
    TEAM_VIEW: 'TEAM_VIEW',
    TEAM_MANAGE: 'TEAM_MANAGE',

    // Financials & Accounting (Executive Only)
    FINANCIALS_VIEW: 'FINANCIALS_VIEW',
    FINANCIALS_MANAGE: 'FINANCIALS_MANAGE',

    // Analytics & System Controls
    ANALYTICS_VIEW: 'ANALYTICS_VIEW',
    SYSTEM_MANAGE: 'SYSTEM_MANAGE',

    // AI Foundation Controls
    AI_VIEW: 'AI_VIEW',
    AI_RUN: 'AI_RUN',
    AI_MANAGE: 'AI_MANAGE'
});

const ALL_PERMISSIONS = Object.values(PERMISSIONS);

/**
 * Baseline Role Capability Matrix
 */
const ROLE_CAPABILITIES = Object.freeze({
    [ROLES.CEO]: ALL_PERMISSIONS,

    [ROLES.MANAGER]: [
        PERMISSIONS.LEADS_VIEW,
        PERMISSIONS.LEADS_CREATE,
        PERMISSIONS.LEADS_ASSIGN,
        PERMISSIONS.LEADS_EDIT,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_EDIT,
        PERMISSIONS.QUOTES_VIEW,
        PERMISSIONS.QUOTES_CREATE,
        PERMISSIONS.QUOTES_EDIT,
        PERMISSIONS.QUOTES_SEND,
        PERMISSIONS.BOOKINGS_VIEW,
        PERMISSIONS.BOOKINGS_CREATE,
        PERMISSIONS.BOOKINGS_EDIT,
        PERMISSIONS.PAYMENTS_VIEW,
        PERMISSIONS.PAYMENTS_CREATE,
        PERMISSIONS.PAYMENTS_EDIT,
        PERMISSIONS.TRIPS_VIEW,
        PERMISSIONS.TRIPS_EDIT,
        PERMISSIONS.COMMUNICATION_VIEW,
        PERMISSIONS.COMMUNICATION_CREATE,
        PERMISSIONS.RESOURCES_VIEW,
        PERMISSIONS.PARTNERS_VIEW,
        PERMISSIONS.TEAM_VIEW,
        PERMISSIONS.ANALYTICS_VIEW,
        PERMISSIONS.AI_VIEW,
        PERMISSIONS.AI_RUN
    ],

    [ROLES.TEAM_LEADER]: [
        PERMISSIONS.LEADS_VIEW,
        PERMISSIONS.LEADS_CREATE,
        PERMISSIONS.LEADS_ASSIGN,
        PERMISSIONS.LEADS_EDIT,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.CUSTOMERS_EDIT,
        PERMISSIONS.BOOKINGS_VIEW,
        PERMISSIONS.TRIPS_VIEW,
        PERMISSIONS.TRIPS_EDIT,
        PERMISSIONS.COMMUNICATION_VIEW,
        PERMISSIONS.COMMUNICATION_CREATE,
        PERMISSIONS.TEAM_VIEW
    ],

    [ROLES.TEAM_MEMBER]: [
        PERMISSIONS.LEADS_VIEW,
        PERMISSIONS.LEADS_CREATE,
        PERMISSIONS.LEADS_EDIT,
        PERMISSIONS.CUSTOMERS_VIEW,
        PERMISSIONS.CUSTOMERS_CREATE,
        PERMISSIONS.TRIPS_VIEW,
        PERMISSIONS.TRIPS_EDIT,
        PERMISSIONS.COMMUNICATION_VIEW,
        PERMISSIONS.COMMUNICATION_CREATE
    ]
});

/**
 * Returns default permissions for a role
 * @param {string} role
 * @returns {string[]}
 */
function getDefaultPermissions(role) {
    const norm = (role || '').toUpperCase();
    return ROLE_CAPABILITIES[norm] ? [...ROLE_CAPABILITIES[norm]] : [];
}

module.exports = {
    PERMISSIONS,
    ALL_PERMISSIONS,
    ROLE_CAPABILITIES,
    getDefaultPermissions
};
