/**
 * AI Customer Hunter Constants & Enums
 * Varanasi Yatra Platform — Prompt 8
 */

// Hunter Operating Modes
const HUNTER_MODES = Object.freeze({
    AI_LOCAL: 'AI_LOCAL',
    AI_OUTSIDE: 'AI_OUTSIDE'
});

const ALL_HUNTER_MODES = Object.freeze(Object.values(HUNTER_MODES));

// Operational System Statuses
const HUNTER_STATUSES = Object.freeze({
    OFFLINE: 'OFFLINE',
    READY: 'READY',
    RUNNING: 'RUNNING',
    PAUSED: 'PAUSED',
    ERROR: 'ERROR',
    EMERGENCY_STOP: 'EMERGENCY_STOP'
});

const ALL_HUNTER_STATUSES = Object.freeze(Object.values(HUNTER_STATUSES));

// Hunter Run Execution Statuses
const HUNTER_RUN_STATUSES = Object.freeze({
    QUEUED: 'QUEUED',
    RUNNING: 'RUNNING',
    COMPLETED: 'COMPLETED',
    PARTIAL: 'PARTIAL',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    BLOCKED: 'BLOCKED'
});

const ALL_HUNTER_RUN_STATUSES = Object.freeze(Object.values(HUNTER_RUN_STATUSES));

// Signal Processing Statuses
const HUNTER_SIGNAL_STATUSES = Object.freeze({
    NEW: 'NEW',
    PROCESSED: 'PROCESSED',
    QUALIFIED: 'QUALIFIED',
    REJECTED: 'REJECTED',
    DUPLICATE: 'DUPLICATE',
    EXPIRED: 'EXPIRED',
    ERROR: 'ERROR'
});

const ALL_HUNTER_SIGNAL_STATUSES = Object.freeze(Object.values(HUNTER_SIGNAL_STATUSES));

// Opportunity Lifecycle Statuses
const HUNTER_OPPORTUNITY_STATUSES = Object.freeze({
    NEW: 'NEW',
    UNDER_REVIEW: 'UNDER_REVIEW',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED',
    CONVERTED: 'CONVERTED',
    DUPLICATE: 'DUPLICATE'
});

const ALL_HUNTER_OPPORTUNITY_STATUSES = Object.freeze(Object.values(HUNTER_OPPORTUNITY_STATUSES));

// Verification & Consent Statuses
const HUNTER_VERIFICATION_STATUSES = Object.freeze({
    UNVERIFIED: 'UNVERIFIED',
    PENDING_REVIEW: 'PENDING_REVIEW',
    HUMAN_VERIFIED: 'HUMAN_VERIFIED',
    CONSENT_CONFIRMED: 'CONSENT_CONFIRMED',
    REJECTED: 'REJECTED'
});

const ALL_HUNTER_VERIFICATION_STATUSES = Object.freeze(Object.values(HUNTER_VERIFICATION_STATUSES));

// Signal Source Types (Section 4)
const HUNTER_SOURCE_TYPES = Object.freeze({
    PUBLIC_SEARCH: 'PUBLIC_SEARCH',
    SEARCH_API: 'SEARCH_API',
    PUBLIC_FEED: 'PUBLIC_FEED',
    PARTNER_FEED: 'PARTNER_FEED',
    PARTNER_REFERRAL: 'PARTNER_REFERRAL',
    FIRST_PARTY: 'FIRST_PARTY',
    FIRST_PARTY_SIGNAL: 'FIRST_PARTY_SIGNAL',
    CONSENTED_INBOUND: 'CONSENTED_INBOUND',
    PUBLIC_DATA_API: 'PUBLIC_DATA_API',
    OTHER_AUTHORIZED_API: 'OTHER_AUTHORIZED_API',
    MOCK: 'MOCK'
});

const ALL_HUNTER_SOURCE_TYPES = Object.freeze(Object.values(HUNTER_SOURCE_TYPES));

// Source Authorization Statuses
const HUNTER_AUTH_STATUSES = Object.freeze({
    AUTHORIZED: 'AUTHORIZED',
    PENDING: 'PENDING',
    REJECTED: 'REJECTED',
    NOT_CONFIGURED: 'NOT_CONFIGURED'
});

const ALL_HUNTER_AUTH_STATUSES = Object.freeze(Object.values(HUNTER_AUTH_STATUSES));

// Source Configuration States (Prompt 9 Section 2)
const HUNTER_CONFIG_STATUSES = Object.freeze({
    NOT_CONFIGURED: 'NOT_CONFIGURED',
    READY: 'READY',
    ERROR: 'ERROR',
    DISABLED: 'DISABLED',
    RATE_LIMITED: 'RATE_LIMITED',
    AUTH_FAILED: 'AUTH_FAILED'
});

const ALL_HUNTER_CONFIG_STATUSES = Object.freeze(Object.values(HUNTER_CONFIG_STATUSES));

// Source Health States (Prompt 9 Section 18)
const HUNTER_HEALTH_STATUSES = Object.freeze({
    HEALTHY: 'HEALTHY',
    DEGRADED: 'DEGRADED',
    ERROR: 'ERROR',
    NOT_CONFIGURED: 'NOT_CONFIGURED',
    DISABLED: 'DISABLED',
    RATE_LIMITED: 'RATE_LIMITED'
});

const ALL_HUNTER_HEALTH_STATUSES = Object.freeze(Object.values(HUNTER_HEALTH_STATUSES));

// Local Hunter Intent Categories (Section 10)
const HUNTER_LOCAL_INTENTS = Object.freeze({
    DARSHAN_NOW: 'DARSHAN_NOW',
    BOAT_NOW: 'BOAT_NOW',
    AARTI_NOW: 'AARTI_NOW',
    TRANSPORT_NOW: 'TRANSPORT_NOW',
    PANDIT_NOW: 'PANDIT_NOW',
    GUIDE_NOW: 'GUIDE_NOW',
    SHOPPING_NOW: 'SHOPPING_NOW',
    LOCAL_PACKAGE: 'LOCAL_PACKAGE',
    SAME_DAY_TRIP: 'SAME_DAY_TRIP',
    NEXT_DAY_TRIP: 'NEXT_DAY_TRIP',
    SHORT_STAY: 'SHORT_STAY'
});

const ALL_HUNTER_LOCAL_INTENTS = Object.freeze(Object.values(HUNTER_LOCAL_INTENTS));

// Outside Hunter Intent Categories (Section 12)
const HUNTER_OUTSIDE_INTENTS = Object.freeze({
    TRIP_PLANNING: 'TRIP_PLANNING',
    HOTEL_SEARCH: 'HOTEL_SEARCH',
    DARSHAN_PLANNING: 'DARSHAN_PLANNING',
    PACKAGE_SEARCH: 'PACKAGE_SEARCH',
    ITINERARY_RESEARCH: 'ITINERARY_RESEARCH',
    TRANSPORT_PLANNING: 'TRANSPORT_PLANNING',
    FAMILY_TRIP: 'FAMILY_TRIP',
    COUPLE_TRIP: 'COUPLE_TRIP',
    GROUP_TRIP: 'GROUP_TRIP'
});

const ALL_HUNTER_OUTSIDE_INTENTS = Object.freeze(Object.values(HUNTER_OUTSIDE_INTENTS));

// Canonical Services Detected (Section 16)
const HUNTER_SERVICES = Object.freeze({
    HOTEL: 'HOTEL',
    DARSHAN: 'DARSHAN',
    BOAT: 'BOAT',
    TRANSPORT: 'TRANSPORT',
    PANDIT: 'PANDIT',
    GUIDE: 'GUIDE',
    SHOPPING: 'SHOPPING',
    PACKAGE: 'PACKAGE',
    AARTI: 'AARTI',
    ITINERARY: 'ITINERARY'
});

const ALL_HUNTER_SERVICES = Object.freeze(Object.values(HUNTER_SERVICES));

// Intent Strength Levels (Section 17)
const HUNTER_INTENT_LEVELS = Object.freeze({
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH'
});

const ALL_HUNTER_INTENT_LEVELS = Object.freeze(Object.values(HUNTER_INTENT_LEVELS));

// Signal Quality Tiers (Section 20)
const HUNTER_QUALITY_TIERS = Object.freeze({
    HIGH_QUALITY: 'HIGH_QUALITY',
    MEDIUM_QUALITY: 'MEDIUM_QUALITY',
    LOW_QUALITY: 'LOW_QUALITY'
});

const ALL_HUNTER_QUALITY_TIERS = Object.freeze(Object.values(HUNTER_QUALITY_TIERS));

// Scheduler Frequencies (Section 35)
const HUNTER_SCHEDULER_FREQUENCIES = Object.freeze({
    MANUAL: 'MANUAL',
    HOURLY: 'HOURLY',
    EVERY_3_HOURS: 'EVERY_3_HOURS',
    DAILY: 'DAILY'
});

const ALL_HUNTER_SCHEDULER_FREQUENCIES = Object.freeze(Object.values(HUNTER_SCHEDULER_FREQUENCIES));

// Canonical Local Areas (Section 42 & 81)
const HUNTER_CANONICAL_AREAS = Object.freeze([
    'Godaulia',
    'Dashashwamedh',
    'Bhelupur',
    'Sarnath',
    'Lanka',
    'BHU',
    'Assi',
    'Cantonment'
]);

// Safety Default Limits (Section 36)
const HUNTER_SAFETY_DEFAULTS = Object.freeze({
    MAX_SIGNALS_PER_RUN: 100,
    MAX_OPPORTUNITIES_PER_RUN: 20,
    MAX_DAILY_SIGNALS: 500,
    MAX_DAILY_OPPORTUNITIES: 100,
    CONFIDENCE_THRESHOLD: 0.65,
    QUALIFICATION_THRESHOLD: 60,
    MAX_SOURCE_RETRIES: 2
});

// Error Codes (Section 32)
const HUNTER_ERROR_CODES = Object.freeze({
    HUNTER_DISABLED: 'HUNTER_DISABLED',
    LOCAL_HUNTER_DISABLED: 'LOCAL_HUNTER_DISABLED',
    OUTSIDE_HUNTER_DISABLED: 'OUTSIDE_HUNTER_DISABLED',
    EMERGENCY_STOP: 'EMERGENCY_STOP',
    SOURCE_NOT_ALLOWED: 'SOURCE_NOT_ALLOWED',
    SOURCE_NOT_CONFIGURED: 'SOURCE_NOT_CONFIGURED',
    SOURCE_UNAVAILABLE: 'SOURCE_UNAVAILABLE',
    AUTH_FAILED: 'AUTH_FAILED',
    RATE_LIMITED: 'RATE_LIMITED',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
    TIMEOUT: 'TIMEOUT',
    INVALID_RESPONSE: 'INVALID_RESPONSE',
    PARSER_ERROR: 'PARSER_ERROR',
    NOT_CONFIGURED: 'NOT_CONFIGURED',
    RUN_LIMIT_EXCEEDED: 'RUN_LIMIT_EXCEEDED',
    SCOPE_VIOLATION: 'SCOPE_VIOLATION',
    UNAUTHORIZED_ACTION: 'UNAUTHORIZED_ACTION',
    PROMPT_INJECTION_DETECTED: 'PROMPT_INJECTION_DETECTED',
    SAFE_MODE_BLOCKED: 'SAFE_MODE_BLOCKED',
    OPPORTUNITY_NOT_FOUND: 'OPPORTUNITY_NOT_FOUND',
    ALREADY_CONVERTED: 'ALREADY_CONVERTED',
    INVALID_PAYLOAD: 'INVALID_PAYLOAD',
    CONTACT_PROVIDER_NOT_CONFIGURED: 'CONTACT_PROVIDER_NOT_CONFIGURED',
    CONTACT_DISCOVERY_FAILED: 'CONTACT_DISCOVERY_FAILED',
    CONTACT_ROUTE_INVALID: 'CONTACT_ROUTE_INVALID'
});

// =========================================================================
// PROMPT 9.8: CONTACTABILITY LAYER CONSTANTS
// =========================================================================

// Contact Route Types — authorized public contact channels only
const CONTACT_ROUTE_TYPES = Object.freeze({
    BUSINESS_WEBSITE: 'BUSINESS_WEBSITE',
    GOOGLE_BUSINESS: 'GOOGLE_BUSINESS',
    SOCIAL_MEDIA: 'SOCIAL_MEDIA',
    PUBLIC_EMAIL: 'PUBLIC_EMAIL',
    PUBLIC_LISTING: 'PUBLIC_LISTING',
    TOURISM_PORTAL: 'TOURISM_PORTAL',
    BUSINESS_DIRECTORY: 'BUSINESS_DIRECTORY',       // Prompt 9.9: JustDial, IndiaMART, Sulekha etc.
    PARTNER_REFERRAL_CONTACT: 'PARTNER_REFERRAL_CONTACT',
    MANUAL_ENTRY: 'MANUAL_ENTRY',
    UNKNOWN: 'UNKNOWN'
});

const ALL_CONTACT_ROUTE_TYPES = Object.freeze(Object.values(CONTACT_ROUTE_TYPES));

// Contactability Status — lifecycle of contact route discovery
const CONTACT_STATUSES = Object.freeze({
    NOT_ATTEMPTED: 'NOT_ATTEMPTED',
    IN_PROGRESS: 'IN_PROGRESS',
    ROUTES_FOUND: 'ROUTES_FOUND',
    NO_ROUTES_FOUND: 'NO_ROUTES_FOUND',
    PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED',
    FAILED: 'FAILED',
    EXPIRED: 'EXPIRED'
});

const ALL_CONTACT_STATUSES = Object.freeze(Object.values(CONTACT_STATUSES));

// Contact Provider Types — enrichment data source classification
const CONTACT_PROVIDER_TYPES = Object.freeze({
    MOCK: 'MOCK',
    GOOGLE_BUSINESS_API: 'GOOGLE_BUSINESS_API',
    PUBLIC_WEB_ENRICHMENT: 'PUBLIC_WEB_ENRICHMENT',
    PARTNER_DATA: 'PARTNER_DATA',
    MANUAL_ENTRY: 'MANUAL_ENTRY'
});

const ALL_CONTACT_PROVIDER_TYPES = Object.freeze(Object.values(CONTACT_PROVIDER_TYPES));

// Contact Route Verification Statuses
const CONTACT_VERIFICATION_STATUSES = Object.freeze({
    UNVERIFIED: 'UNVERIFIED',
    HUMAN_VERIFIED: 'HUMAN_VERIFIED',
    STALE: 'STALE',
    REJECTED: 'REJECTED'
});

const ALL_CONTACT_VERIFICATION_STATUSES = Object.freeze(Object.values(CONTACT_VERIFICATION_STATUSES));


// =========================================================================
// PROMPT 9.9: ACTIONABILITY, ENRICHMENT & HUMAN SALES CONSTANTS
// =========================================================================

// Actionability Score Tiers (0–100)
const ACTIONABILITY_TIERS = Object.freeze({
    LOW: 'LOW',             // 0–39
    WEAK: 'WEAK',           // 40–59
    ACTIONABLE: 'ACTIONABLE',       // 60–79
    HIGH_PRIORITY: 'HIGH_PRIORITY'  // 80–100
});

const ALL_ACTIONABILITY_TIERS = Object.freeze(Object.values(ACTIONABILITY_TIERS));

// Contact Data Freshness
const CONTACT_FRESHNESS_STATUSES = Object.freeze({
    FRESH: 'FRESH',     // verified within 30 days
    STALE: 'STALE',     // older than 30 days
    UNKNOWN: 'UNKNOWN'  // never verified
});

const ALL_CONTACT_FRESHNESS_STATUSES = Object.freeze(Object.values(CONTACT_FRESHNESS_STATUSES));

// Human Sales Outcomes (recorded by human after contacting prospect)
const HUMAN_CONTACT_OUTCOMES = Object.freeze({
    GENUINE: 'GENUINE',
    NOT_GENUINE: 'NOT_GENUINE',
    FOLLOW_UP_REQUIRED: 'FOLLOW_UP_REQUIRED',
    NO_RESPONSE: 'NO_RESPONSE',
    WRONG_CONTACT: 'WRONG_CONTACT',
    ALREADY_BOOKED: 'ALREADY_BOOKED',
    NOT_INTERESTED: 'NOT_INTERESTED'
});

const ALL_HUMAN_CONTACT_OUTCOMES = Object.freeze(Object.values(HUMAN_CONTACT_OUTCOMES));

// Phone/Email Availability Statuses
const CONTACT_FIELD_AVAILABILITY = Object.freeze({
    AVAILABLE: 'AVAILABLE',
    NOT_AVAILABLE: 'NOT_AVAILABLE',
    UNVERIFIED: 'UNVERIFIED'
});

const ALL_CONTACT_FIELD_AVAILABILITY = Object.freeze(Object.values(CONTACT_FIELD_AVAILABILITY));

// Authorized Contact Provider Data Types (Section 8)
const AUTHORIZED_PROVIDER_DATA_TYPES = Object.freeze({
    PUBLIC_BUSINESS_DATA: 'PUBLIC_BUSINESS_DATA',
    PUBLIC_DIRECTORY: 'PUBLIC_DIRECTORY',
    PUBLIC_BUSINESS_PROFILE: 'PUBLIC_BUSINESS_PROFILE',
    AUTHORIZED_CONTACT_PROVIDER: 'AUTHORIZED_CONTACT_PROVIDER',
    PARTNER_PROVIDED_CONTACT: 'PARTNER_PROVIDED_CONTACT',
    FIRST_PARTY_CONTACT: 'FIRST_PARTY_CONTACT',
    MANUAL_VERIFIED_CONTACT: 'MANUAL_VERIFIED_CONTACT'
});

const ALL_AUTHORIZED_PROVIDER_DATA_TYPES = Object.freeze(Object.values(AUTHORIZED_PROVIDER_DATA_TYPES));

// Signal Intent Classification Categories (Prompt 9.9 Section 4)
const SIGNAL_INTENT_CATEGORIES = Object.freeze({
    INFORMATIONAL: 'INFORMATIONAL',
    EARLY_INTENT: 'EARLY_INTENT',
    PLANNING_INTENT: 'PLANNING_INTENT',
    HIGH_INTENT: 'HIGH_INTENT',
    IRRELEVANT: 'IRRELEVANT',
    SPAM: 'SPAM',
    INJECTION_ATTEMPT: 'INJECTION_ATTEMPT'
});

const ALL_SIGNAL_INTENT_CATEGORIES = Object.freeze(Object.values(SIGNAL_INTENT_CATEGORIES));

// Audit Events for Contact Enrichment
const CONTACT_ENRICHMENT_AUDIT_EVENTS = Object.freeze({
    REQUESTED: 'CONTACT_ENRICHMENT_REQUESTED',
    SUCCESS: 'CONTACT_ENRICHMENT_SUCCESS',
    FAILED: 'CONTACT_ENRICHMENT_FAILED',
    ROUTE_ADDED: 'CONTACT_ROUTE_ADDED',
    ROUTE_VERIFIED: 'CONTACT_ROUTE_VERIFIED',
    ROUTE_REJECTED: 'CONTACT_ROUTE_REJECTED',
    OUTCOME_RECORDED: 'CONTACT_OUTCOME_RECORDED'
});

const ALL_CONTACT_ENRICHMENT_AUDIT_EVENTS = Object.freeze(Object.values(CONTACT_ENRICHMENT_AUDIT_EVENTS));


// =========================================================================
// PROMPT 9.10: REAL-PROSPECT QUALITY & HUMAN GATE CONSTANTS
// =========================================================================

// Commercial Intent Categories (Section 2)
const COMMERCIAL_INTENT_CATEGORIES = Object.freeze({
    INFORMATIONAL: 'INFORMATIONAL',
    INSPIRATIONAL: 'INSPIRATIONAL',
    PLANNING: 'PLANNING',
    ACTIVE_TRAVEL_PLANNING: 'ACTIVE_TRAVEL_PLANNING',
    COMMERCIAL_TRIP_REQUEST: 'COMMERCIAL_TRIP_REQUEST',
    UNKNOWN: 'UNKNOWN'
});

const ALL_COMMERCIAL_INTENT_CATEGORIES = Object.freeze(Object.values(COMMERCIAL_INTENT_CATEGORIES));

// Human Review & Funnel Lifecycle States (Section 5)
const HUNTER_LIFECYCLE_STATES = Object.freeze({
    DISCOVERED: 'DISCOVERED',
    RELEVANT: 'RELEVANT',
    QUALIFIED: 'QUALIFIED',
    ACTIONABLE: 'ACTIONABLE',
    CONTACTABLE: 'CONTACTABLE',
    HUMAN_REVIEW: 'HUMAN_REVIEW',
    CONTACTED: 'CONTACTED',
    GENUINE: 'GENUINE',
    NOT_GENUINE: 'NOT_GENUINE',
    FOLLOW_UP_REQUIRED: 'FOLLOW_UP_REQUIRED',
    NO_RESPONSE: 'NO_RESPONSE',
    WRONG_CONTACT: 'WRONG_CONTACT',
    ALREADY_BOOKED: 'ALREADY_BOOKED',
    NOT_INTERESTED: 'NOT_INTERESTED',
    STALE: 'STALE',
    CRM_LEAD: 'CRM_LEAD'
});

const ALL_HUNTER_LIFECYCLE_STATES = Object.freeze(Object.values(HUNTER_LIFECYCLE_STATES));

// Route Verification Statuses (Section 4)
const ROUTE_VERIFICATION_STATUSES = Object.freeze({
    VERIFIED: 'VERIFIED',
    UNVERIFIED: 'UNVERIFIED',
    STALE: 'STALE',
    REJECTED: 'REJECTED',
    NOT_FOUND: 'NOT_FOUND',
    PROVIDER_NOT_CONFIGURED: 'PROVIDER_NOT_CONFIGURED'
});

const ALL_ROUTE_VERIFICATION_STATUSES = Object.freeze(Object.values(ROUTE_VERIFICATION_STATUSES));

// Opportunity Staleness States (Section 9)
const STALENESS_STATUSES = Object.freeze({
    FRESH: 'FRESH',
    AGING: 'AGING',
    STALE: 'STALE',
    EXPIRED: 'EXPIRED',
    CLOSED: 'CLOSED'
});

const ALL_STALENESS_STATUSES = Object.freeze(Object.values(STALENESS_STATUSES));

// Recommended Advisory Next Actions (Section 10)
const RECOMMENDED_NEXT_ACTIONS = Object.freeze({
    HUMAN_REVIEW: 'HUMAN_REVIEW',
    VERIFY_CONTACT_ROUTE: 'VERIFY_CONTACT_ROUTE',
    INITIATE_HUMAN_CONTACT: 'INITIATE_HUMAN_CONTACT',
    DISCUSS_REQUIREMENTS: 'DISCUSS_REQUIREMENTS',
    CREATE_QUOTE: 'CREATE_QUOTE',
    CRM_LEAD_CONVERSION: 'CRM_LEAD_CONVERSION',
    MARK_NOT_GENUINE: 'MARK_NOT_GENUINE',
    NO_ACTION_STALE: 'NO_ACTION_STALE'
});

const ALL_RECOMMENDED_NEXT_ACTIONS = Object.freeze(Object.values(RECOMMENDED_NEXT_ACTIONS));

module.exports = {
    HUNTER_MODES,
    ALL_HUNTER_MODES,
    HUNTER_STATUSES,
    ALL_HUNTER_STATUSES,
    HUNTER_RUN_STATUSES,
    ALL_HUNTER_RUN_STATUSES,
    HUNTER_SIGNAL_STATUSES,
    ALL_HUNTER_SIGNAL_STATUSES,
    HUNTER_OPPORTUNITY_STATUSES,
    ALL_HUNTER_OPPORTUNITY_STATUSES,
    HUNTER_VERIFICATION_STATUSES,
    ALL_HUNTER_VERIFICATION_STATUSES,
    HUNTER_SOURCE_TYPES,
    ALL_HUNTER_SOURCE_TYPES,
    HUNTER_AUTH_STATUSES,
    ALL_HUNTER_AUTH_STATUSES,
    HUNTER_CONFIG_STATUSES,
    ALL_HUNTER_CONFIG_STATUSES,
    HUNTER_HEALTH_STATUSES,
    ALL_HUNTER_HEALTH_STATUSES,
    HUNTER_LOCAL_INTENTS,
    ALL_HUNTER_LOCAL_INTENTS,
    HUNTER_OUTSIDE_INTENTS,
    ALL_HUNTER_OUTSIDE_INTENTS,
    HUNTER_SERVICES,
    ALL_HUNTER_SERVICES,
    HUNTER_INTENT_LEVELS,
    ALL_HUNTER_INTENT_LEVELS,
    HUNTER_QUALITY_TIERS,
    ALL_HUNTER_QUALITY_TIERS,
    HUNTER_SCHEDULER_FREQUENCIES,
    ALL_HUNTER_SCHEDULER_FREQUENCIES,
    HUNTER_CANONICAL_AREAS,
    HUNTER_SAFETY_DEFAULTS,
    HUNTER_ERROR_CODES,
    CONTACT_ROUTE_TYPES,
    ALL_CONTACT_ROUTE_TYPES,
    CONTACT_STATUSES,
    ALL_CONTACT_STATUSES,
    CONTACT_PROVIDER_TYPES,
    ALL_CONTACT_PROVIDER_TYPES,
    CONTACT_VERIFICATION_STATUSES,
    ALL_CONTACT_VERIFICATION_STATUSES,
    // Prompt 9.9
    ACTIONABILITY_TIERS,
    ALL_ACTIONABILITY_TIERS,
    CONTACT_FRESHNESS_STATUSES,
    ALL_CONTACT_FRESHNESS_STATUSES,
    HUMAN_CONTACT_OUTCOMES,
    ALL_HUMAN_CONTACT_OUTCOMES,
    CONTACT_FIELD_AVAILABILITY,
    ALL_CONTACT_FIELD_AVAILABILITY,
    AUTHORIZED_PROVIDER_DATA_TYPES,
    ALL_AUTHORIZED_PROVIDER_DATA_TYPES,
    SIGNAL_INTENT_CATEGORIES,
    ALL_SIGNAL_INTENT_CATEGORIES,
    CONTACT_ENRICHMENT_AUDIT_EVENTS,
    ALL_CONTACT_ENRICHMENT_AUDIT_EVENTS,
    // Prompt 9.10
    COMMERCIAL_INTENT_CATEGORIES,
    ALL_COMMERCIAL_INTENT_CATEGORIES,
    HUNTER_LIFECYCLE_STATES,
    ALL_HUNTER_LIFECYCLE_STATES,
    ROUTE_VERIFICATION_STATUSES,
    ALL_ROUTE_VERIFICATION_STATUSES,
    STALENESS_STATUSES,
    ALL_STALENESS_STATUSES,
    RECOMMENDED_NEXT_ACTIONS,
    ALL_RECOMMENDED_NEXT_ACTIONS
};


