/**
 * Canonical Constants & Enums for AI Foundation
 * Varanasi Yatra Platform — Prompt 5
 */

// AI Modules
const AI_MODULES = Object.freeze({
    CUSTOMER_ASSISTANT: 'CUSTOMER_ASSISTANT',
    SALES_ASSISTANT: 'SALES_ASSISTANT',
    CUSTOMER_HUNTER: 'CUSTOMER_HUNTER',
    LOCAL_HUNTER: 'LOCAL_HUNTER',
    OUTSIDE_HUNTER: 'OUTSIDE_HUNTER',
    VOICE_AI: 'VOICE_AI',
    SYSTEM_ANALYSIS: 'SYSTEM_ANALYSIS'
});

const ALL_AI_MODULES = Object.freeze(Object.values(AI_MODULES));

// AI Run Statuses
const AI_RUN_STATUSES = Object.freeze({
    QUEUED: 'QUEUED',
    RUNNING: 'RUNNING',
    COMPLETED: 'COMPLETED',
    FAILED: 'FAILED',
    CANCELLED: 'CANCELLED',
    BLOCKED: 'BLOCKED'
});

const ALL_AI_RUN_STATUSES = Object.freeze(Object.values(AI_RUN_STATUSES));

// Audit Decisions
const AI_AUDIT_DECISIONS = Object.freeze({
    ALLOWED: 'ALLOWED',
    BLOCKED: 'BLOCKED',
    APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
    FAILED: 'FAILED'
});

const ALL_AI_AUDIT_DECISIONS = Object.freeze(Object.values(AI_AUDIT_DECISIONS));

// Risk Levels for Tools
const AI_RISK_LEVELS = Object.freeze({
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH',
    CRITICAL: 'CRITICAL'
});

const ALL_AI_RISK_LEVELS = Object.freeze(Object.values(AI_RISK_LEVELS));

// Future Hunter Opportunity Sources
const AI_OPPORTUNITY_SOURCES = Object.freeze({
    AI_LOCAL: 'AI_LOCAL',
    AI_OUTSIDE: 'AI_OUTSIDE'
});

const ALL_AI_OPPORTUNITY_SOURCES = Object.freeze(Object.values(AI_OPPORTUNITY_SOURCES));

// Opportunity Lifecycle Statuses
const AI_OPPORTUNITY_STATUSES = Object.freeze({
    NEW: 'NEW',
    UNDER_REVIEW: 'UNDER_REVIEW',
    APPROVED: 'APPROVED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED',
    CONVERTED: 'CONVERTED'
});

const ALL_AI_OPPORTUNITY_STATUSES = Object.freeze(Object.values(AI_OPPORTUNITY_STATUSES));

// Opportunity Verification Statuses
const AI_VERIFICATION_STATUSES = Object.freeze({
    UNVERIFIED: 'UNVERIFIED',
    PENDING_REVIEW: 'PENDING_REVIEW',
    HUMAN_VERIFIED: 'HUMAN_VERIFIED',
    CONSENT_CONFIRMED: 'CONSENT_CONFIRMED',
    REJECTED: 'REJECTED'
});

const ALL_AI_VERIFICATION_STATUSES = Object.freeze(Object.values(AI_VERIFICATION_STATUSES));

// Supported Providers
const AI_PROVIDERS = Object.freeze({
    MOCK: 'mock',
    OPENAI: 'openai',
    GEMINI: 'gemini',
    ANTHROPIC: 'anthropic'
});

// Error Codes
const AI_ERROR_CODES = Object.freeze({
    AI_DISABLED: 'AI_DISABLED',
    SAFE_MODE_BLOCKED: 'SAFE_MODE_BLOCKED',
    EMERGENCY_STOP: 'EMERGENCY_STOP',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    TOOL_DISABLED: 'TOOL_DISABLED',
    TOOL_SCOPE_DENIED: 'TOOL_SCOPE_DENIED',
    RATE_LIMITED: 'RATE_LIMITED',
    MODULE_DISABLED: 'MODULE_DISABLED',
    PROVIDER_ERROR: 'PROVIDER_ERROR',
    INVALID_REQUEST: 'INVALID_REQUEST'
});

// Assistant Conversation States (Prompt 6)
const AI_ASSISTANT_STATES = Object.freeze({
    NEW: 'NEW',
    DISCOVERY: 'DISCOVERY',
    COLLECTING_DETAILS: 'COLLECTING_DETAILS',
    READY_FOR_CONFIRMATION: 'READY_FOR_CONFIRMATION',
    AWAITING_CONTACT: 'AWAITING_CONTACT',
    AWAITING_CONSENT: 'AWAITING_CONSENT',
    SUBMITTED: 'SUBMITTED',
    HANDOFF_REQUIRED: 'HANDOFF_REQUIRED',
    COMPLETED: 'COMPLETED',
    ABANDONED: 'ABANDONED',
    ERROR: 'ERROR'
});

const ALL_AI_ASSISTANT_STATES = Object.freeze(Object.values(AI_ASSISTANT_STATES));

// Service Intents
const AI_SERVICE_INTENTS = Object.freeze({
    HOTEL: 'HOTEL',
    DARSHAN: 'DARSHAN',
    BOAT: 'BOAT',
    TRANSPORT: 'TRANSPORT',
    PANDIT: 'PANDIT',
    GUIDE: 'GUIDE',
    SHOPPING: 'SHOPPING',
    PACKAGE: 'PACKAGE',
    EXPERIENCE: 'EXPERIENCE',
    MULTI_SERVICE: 'MULTI_SERVICE'
});

const ALL_AI_SERVICE_INTENTS = Object.freeze(Object.values(AI_SERVICE_INTENTS));

// Escalation Triggers for Human Handoff
const AI_ESCALATION_TRIGGERS = Object.freeze({
    PRICE_REQUEST: 'PRICE_REQUEST',
    AVAILABILITY_CONFIRMATION: 'AVAILABILITY_CONFIRMATION',
    BOOKING_COMMITMENT: 'BOOKING_COMMITMENT',
    PAYMENT_ISSUE: 'PAYMENT_ISSUE',
    COMPLAINT: 'COMPLAINT',
    HUMAN_REQUEST: 'HUMAN_REQUEST',
    UNRECOGNIZED_QUERY: 'UNRECOGNIZED_QUERY'
});

const ALL_AI_ESCALATION_TRIGGERS = Object.freeze(Object.values(AI_ESCALATION_TRIGGERS));

// Sales Assistant Intent Levels (Prompt 7)
const AI_SALES_INTENT_LEVELS = Object.freeze({
    LOW: 'LOW',
    MEDIUM: 'MEDIUM',
    HIGH: 'HIGH'
});

const ALL_AI_SALES_INTENT_LEVELS = Object.freeze(Object.values(AI_SALES_INTENT_LEVELS));

// Purchase Readiness Stages (Prompt 7)
const AI_PURCHASE_READINESS = Object.freeze({
    EARLY_RESEARCH: 'EARLY_RESEARCH',
    PLANNING: 'PLANNING',
    SHORTLISTING: 'SHORTLISTING',
    READY_TO_BOOK: 'READY_TO_BOOK'
});

const ALL_AI_PURCHASE_READINESS = Object.freeze(Object.values(AI_PURCHASE_READINESS));

// Additive AI Sales Stages (Prompt 7 Section 7)
const AI_SALES_STAGES = Object.freeze({
    NEW: 'NEW',
    QUALIFYING: 'QUALIFYING',
    REQUIREMENT_COMPLETE: 'REQUIREMENT_COMPLETE',
    QUOTE_READY: 'QUOTE_READY',
    QUOTE_SENT: 'QUOTE_SENT',
    NEGOTIATION: 'NEGOTIATION',
    DECISION_PENDING: 'DECISION_PENDING',
    BOOKING_READY: 'BOOKING_READY',
    STALLED: 'STALLED',
    LOST_RISK: 'LOST_RISK'
});

const ALL_AI_SALES_STAGES = Object.freeze(Object.values(AI_SALES_STAGES));

// Next Best Action Types (Prompt 7 Section 9)
const AI_NEXT_ACTIONS = Object.freeze({
    CONFIRM_TRAVEL_DATES: 'CONFIRM_TRAVEL_DATES',
    CONFIRM_GUEST_COUNT: 'CONFIRM_GUEST_COUNT',
    ASK_HOTEL_PREFERENCE: 'ASK_HOTEL_PREFERENCE',
    ASK_BUDGET_RANGE: 'ASK_BUDGET_RANGE',
    FOLLOW_UP: 'FOLLOW_UP',
    SEND_REQUIREMENT_SUMMARY: 'SEND_REQUIREMENT_SUMMARY',
    PREPARE_QUOTE_DRAFT: 'PREPARE_QUOTE_DRAFT',
    REQUEST_HUMAN_REVIEW: 'REQUEST_HUMAN_REVIEW',
    ESCALATE_TO_MANAGER: 'ESCALATE_TO_MANAGER'
});

const ALL_AI_NEXT_ACTIONS = Object.freeze(Object.values(AI_NEXT_ACTIONS));

// Follow-Up Timings & Priorities (Prompt 7 Section 11)
const AI_FOLLOWUP_TIMINGS = Object.freeze({
    URGENT: 'URGENT',
    TODAY: 'TODAY',
    SOON: 'SOON',
    LATER: 'LATER',
    NO_ACTION: 'NO_ACTION'
});

const ALL_AI_FOLLOWUP_TIMINGS = Object.freeze(Object.values(AI_FOLLOWUP_TIMINGS));

// Objection Types (Prompt 7 Section 15)
const AI_OBJECTION_TYPES = Object.freeze({
    PRICE: 'PRICE',
    PRICE_COMPARISON: 'PRICE_COMPARISON',
    TRUST: 'TRUST',
    TIMING: 'TIMING',
    AVAILABILITY: 'AVAILABILITY',
    HOTEL_PREFERENCE: 'HOTEL_PREFERENCE',
    SERVICE_SCOPE: 'SERVICE_SCOPE',
    FAMILY_CONCERN: 'FAMILY_CONCERN',
    UNCERTAINTY: 'UNCERTAINTY',
    DELAY: 'DELAY',
    CUSTOM_REQUEST: 'CUSTOM_REQUEST'
});

const ALL_AI_OBJECTION_TYPES = Object.freeze(Object.values(AI_OBJECTION_TYPES));

// Sentiment Categories (Prompt 7 Section 14)
const AI_SENTIMENTS = Object.freeze({
    POSITIVE: 'POSITIVE',
    NEUTRAL: 'NEUTRAL',
    UNCERTAIN: 'UNCERTAIN',
    CONCERNED: 'CONCERNED',
    FRUSTRATED: 'FRUSTRATED'
});

const ALL_AI_SENTIMENTS = Object.freeze(Object.values(AI_SENTIMENTS));

// Recommendation Lifecycle Statuses (Prompt 7 Section 47)
const AI_RECOMMENDATION_STATUSES = Object.freeze({
    NEW: 'NEW',
    VIEWED: 'VIEWED',
    ACCEPTED: 'ACCEPTED',
    EDITED: 'EDITED',
    REJECTED: 'REJECTED',
    EXPIRED: 'EXPIRED'
});

const ALL_AI_RECOMMENDATION_STATUSES = Object.freeze(Object.values(AI_RECOMMENDATION_STATUSES));

module.exports = {
    AI_MODULES,
    ALL_AI_MODULES,
    AI_RUN_STATUSES,
    ALL_AI_RUN_STATUSES,
    AI_AUDIT_DECISIONS,
    ALL_AI_AUDIT_DECISIONS,
    AI_RISK_LEVELS,
    ALL_AI_RISK_LEVELS,
    AI_OPPORTUNITY_SOURCES,
    ALL_AI_OPPORTUNITY_SOURCES,
    AI_OPPORTUNITY_STATUSES,
    ALL_AI_OPPORTUNITY_STATUSES,
    AI_VERIFICATION_STATUSES,
    ALL_AI_VERIFICATION_STATUSES,
    AI_PROVIDERS,
    AI_ERROR_CODES,
    AI_ASSISTANT_STATES,
    ALL_AI_ASSISTANT_STATES,
    AI_SERVICE_INTENTS,
    ALL_AI_SERVICE_INTENTS,
    AI_ESCALATION_TRIGGERS,
    ALL_AI_ESCALATION_TRIGGERS,
    AI_SALES_INTENT_LEVELS,
    ALL_AI_SALES_INTENT_LEVELS,
    AI_PURCHASE_READINESS,
    ALL_AI_PURCHASE_READINESS,
    AI_SALES_STAGES,
    ALL_AI_SALES_STAGES,
    AI_NEXT_ACTIONS,
    ALL_AI_NEXT_ACTIONS,
    AI_FOLLOWUP_TIMINGS,
    ALL_AI_FOLLOWUP_TIMINGS,
    AI_OBJECTION_TYPES,
    ALL_AI_OBJECTION_TYPES,
    AI_SENTIMENTS,
    ALL_AI_SENTIMENTS,
    AI_RECOMMENDATION_STATUSES,
    ALL_AI_RECOMMENDATION_STATUSES
};
